---
- name: add escapace gpg keys
  ansible.builtin.rpm_key:
    state: present
    key: https://releases.escapace.com/GPG-KEY-ESCAPACE

- name: add escapace repository
  ansible.builtin.get_url:
    url: https://releases.escapace.com/stable/linux/centos/escapace.repo
    dest: /etc/yum.repos.d/escapace.repo
    owner: root
    group: root
    mode: "0644"
